ignore:
  - "cmd/"
  - "tests/"
comment:
  # Show the comment only on coverage changes
  require_changes: true
  layout: "reach, condensed_files, diff"
coverage:
  # Show the Codecov status without waiting for other status checks to complete or pass
  require_ci_to_pass: false
  status:
    project:
      default:
        # See status checks but prevent them from blocking
        informational: true
    patch:
      default:
        informational: true
github_checks:
  annotations: false
