name: build
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        compiler: [g++, clang++]
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        if: ${{ matrix.compiler == 'g++' }}
        run: sudo apt install -y g++
      - name: Configure CMake
        run: CXX=${{ matrix.compiler }} cmake -B build
      - name: Build
        run: cmake --build build