name: codecov
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt install -y gcovr
      - name: Configure CMake
        run: cmake -B build
      - name: Build
        run: cmake --build build
      - name: Run tests
        working-directory: build
        run: ctest -j
      - name: Generate coverage report
        run: gcovr --xml coverage.xml -f internal/ build/tests/
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          file: coverage.xml
          flags: unittests
          name: webserv
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true