name: ctest
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  run:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure CMake
        run: cmake -B build
      - name: Build
        run: cmake --build build
      - name: Test
        working-directory: build
        run: ctest -j
