name: ctest
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure CMake
        run: CXX=clang++ cmake -B build
      - name: Build
        run: cmake --build build
      - name: Test
        id: test
        working-directory: build
        run: ctest
      - name: Upload Test Log
        if: failure() && steps.test.outcome == 'failure'
        uses: actions/upload-artifact@v2
        with:
          name: TestLog
          path: build/Testing/Temporary/LastTest.log
