name: format
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  run:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: clang-format
          version: 1.0
      - name: Run clang-format
        run: clang-format -i $(git ls-files '*.cpp' '*.hpp')
      - name: Check for changes
        run: git diff --exit-code