name: lint
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install clang-tidy
        run: sudo apt-get install -y clang-tidy
      - name: Configure cmake
        run: cmake -B build
      - name: Run clang-tidy
        run: clang-tidy -p build -warnings-as-errors '*,-clang-diagnostic-unused-parameter' $(git ls-files '*.cpp' '*.hpp')
