name: lint
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install clang-tidy
        run: sudo apt-get install -y clang-tidy
      - name: Configure cmake
        run: cmake -B build
      - name: Build
        run: cmake --build build
      - name: Run clang-tidy
        run: run-clang-tidy -q -p build -j $(nproc)
