name: lint
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: clang-tidy
          version: 1.0
      - name: Configure cmake
        run: cmake -B build
      - name: Run clang-tidy
        run: clang-tidy -p build $(git ls-files '*.cpp' '*.hpp')
